# all (default)
#   Create all the necessary directories, javascript, css, etc.
#
# prod
#   Create static assets for production. Requires the following additional dependencies:
#   - uglifyjs
#   - zopfli
#   - brotli
#   - pandoc
#
# chmod
#   For when the http process is run from a different user than the files are
#   chown'ed to. chmods all files and directories written to from vndb.pl.
#
# multi-start, multi-stop, multi-restart:
#   Start/stop/restart the Multi daemon. Provided for convenience, a proper initscript
#   probably makes more sense.
#
# NOTE: This Makefile has only been tested using GNU make in a relatively
#   up-to-date Gentoo & Alpine Linux environment, it may not work in other
#   environments. Patches to improve the portability are always welcome.


.PHONY: all prod clean cleaner chmod test multi-stop multi-start multi-restart

JS_BUNDLE_NAMES=$(shell ls -d js/*/ | sed 's#js/\(.\+\)/#\1#g')
JS_BUNDLE_INDICES=$(shell echo js/*/index.js)
JS_BUNDLE_OUT=$(shell ls -d js/*/ | sed 's#js/\(.\+\)/#static/g/\1.js#g')
JS_BUNDLE_MIN=$(shell ls -d js/*/ | sed 's#js/\(.\+\)/#static/g/\1.min.js#g')
JS_BUNDLE_GZ=$(shell ls -d js/*/ | sed 's#js/\(.\+\)/#static/g/\1.min.js.gz#g')
JS_BUNDLE_BR=$(shell ls -d js/*/ | sed 's#js/\(.\+\)/#static/g/\1.min.js.br#g')
CSS_OUT=$(shell ls css/skins/*.sass | sed -e 's/css\/skins\/\(.\+\)\.sass/static\/g\/\1.css/g')
CSS_GZ=$(shell ls css/skins/*.sass | sed -e 's/css\/skins\/\(.\+\)\.sass/static\/g\/\1.css.gz/g')
CSS_BR=$(shell ls css/skins/*.sass | sed -e 's/css\/skins\/\(.\+\)\.sass/static\/g\/\1.css.br/g')

IMG_DIRS=\
	static/ch static/cv static/sf static/st \
	static/ch.orig static/cv.orig static/sf.orig

ALL_KEEP=\
	${IMG_DIRS} \
	data/log static/g www \
	data/conf.pl \
	www/robots.txt static/robots.txt

ALL_CLEAN=\
	imgproc/imgproc-portable \
	static/g/elm.js \
	static/g/icons.svg \
	static/g/icons.png \
	sql/editfunc.sql \
	${JS_BUNDLE_OUT} \
	${CSS_OUT}

PROD=\
	static/g/api-nyan.html static/g/api-kana.html\
	static/g/elm.min.js static/g/elm.min.js.gz static/g/elm.min.js.br\
	static/g/icons.svg.gz static/g/icons.svg.br\
	static/g/icons.opt.png \
	${JS_BUNDLE_GZ} ${JS_BUNDLE_BR} \
	${CSS_GZ} ${CSS_BR}

all: ${ALL_KEEP} ${ALL_CLEAN}
prod: all ${PROD}

clean:
	rm -f ${ALL_CLEAN} ${PROD}
	rm -rf static/g/
	rm -rf elm/Gen/
	rm -rf elm/elm-stuff/build-artifacts
	rm -rf js/.gen/deps.mk
	$(MAKE) -C sql/c clean

cleaner: clean
	rm -rf elm/elm-stuff js/.gen
	make -C imgproc distclean

sql/editfunc.sql: util/sqleditfunc.pl sql/schema.sql
	util/sqleditfunc.pl

imgproc/imgproc-portable: imgproc/imgproc.c
	make -C imgproc

${IMG_DIRS}:
	mkdir -p $@;
	for i in $$(seq -w 0 1 99); do mkdir -p "$@/$$i"; done

data/log www static/g js/.gen:
	mkdir -p $@

data/conf.pl:
	cp -n data/conf_example.pl data/conf.pl

%/robots.txt: | www
	echo 'User-agent: *' > $@
	echo 'Disallow: /' >> $@

%.gz: %
	zopfli $<

%.br: %
	brotli -f $< && touch $@

chmod: all
	chmod -R a-x+rwX ${IMG_DIRS}

test: all
	prove util/bbcode-test.pl
	if [ -e imgproc/imgproc-custom ]; then cd imgproc && ./test-custom.pl; fi

# Single rule for svg & png sprites. This uses a GNU multiple pattern rule in
# order to have it parallelize correctly - splitting this up into two
# individual rules is buggy.
static/g/%.spritecss static/g/icons.%: util/%sprite.pl icons icons/* icons/*/* | static/g
	$<

static/g/png.spritecss static/g/icons.png: imgproc/imgproc-portable

static/g/icons.opt.png: static/g/icons.png
	rm -f $@
	zopflipng -m --lossy_transparent $< $@

static/g/%.css: css/skins/%.sass css/*.css static/g/png.spritecss static/g/svg.spritecss | static/g
	( echo '$$png-version: "$(shell sha1sum static/g/icons.png | head -c8)";'; \
	  echo '$$svg-version: "$(shell sha1sum static/g/icons.svg | head -c8)";'; \
	  echo '@import "css/skins/$*"' ) | sassc --stdin -I. --style compressed >$@

static/g/api-%.html: data/api-%.md
	pandoc "$<" -st html5 --toc -o "$@"



ELM_FILES=elm/*.elm elm/*/*.elm
ELM_MODULES=$(shell grep -l '^main =' ${ELM_FILES} | sed 's/^elm\///')

# Patch the Javascript generated by Elm:
# - Add @license and @source comments
# - Redirect calls from Lib.Ffi.* to window.elmFfi_*
# - Patch the virtualdom diffing algorithm to always apply the 'selected' attribute
# - Patch the Regex library to always enable the 'u' flag
define fix-elm
	( echo '// @license magnet:?xt=urn:btih:0b31508aeb0634b347b8270c7bee4d411b5d4109&dn=agpl-3.0.txt AGPL-3.0-only'; \
	  echo '// @license magnet:?xt=urn:btih:c80d50af7d3db9be66a4d0a86db0286e4fd33292&dn=bsd-3-clause.txt BSD-3-Clause'; \
	  echo '// @source: https://code.blicky.net/yorhel/vndb/src/branch/master/elm'; \
	  echo '// SPDX-License-Identifier: AGPL-3.0-only and BSD-3-Clause'; \
	  cat $@; \
	  echo; \
	  echo '// @license-end' \
	)   | sed 's/var \$$author\$$project\$$Lib\$$Ffi\$$/var __unused__/g' \
		| sed -E 's/\$$author\$$project\$$Lib\$$Ffi\$$([a-zA-Z0-9_]+)/window.elmFfi_\1(_Json_wrap,_Browser_call)/g' \
		| sed -E "s/([^ ]+) !== 'checked'/\\1 !== 'checked' \&\& \\1 !== 'selected'/g" \
		| sed -E "s/var flags = 'g'/var flags = 'gu'/g" >$@~
	mv $@~ $@
endef

elm/Gen/.generated: lib/VNWeb/*.pm lib/VNWeb/*/*.pm lib/VNDB/Types.pm lib/VNDB/ExtLinks.pm lib/VNDB/Config.pm data/conf.pl
	util/vndb.pl elmgen

static/g/elm.js: ${ELM_FILES} elm/Gen/.generated | static/g
	cd elm && ELM_HOME=elm-stuff elm make ${ELM_MODULES} --output ../$@
	${fix-elm}

static/g/elm.min.js: ${ELM_FILES} elm/Gen/.generated | static/g
	cd elm && ELM_HOME=elm-stuff elm make --optimize ${ELM_MODULES} --output ../$@
	${fix-elm}
	uglifyjs $@ --comments '/(@license|@source|SPDX-)/' --compress \
		'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe'\
		| uglifyjs --mangle --comments all -o $@~
	mv $@~ $@

js/.gen/deps.mk: ${JS_BUNDLE_INDICES} | js/.gen
	for f in ${JS_BUNDLE_NAMES}; do \
		deps=$$(grep '^@include ' js/$$f/index.js | sed "s/@include / js\//" | tr -d '\n'); \
		echo "static/g/$$f.js: js/$$f/index.js$$deps";echo; \
	done >$@

include js/.gen/deps.mk

js/.gen/mithril.js: | js/.gen
	curl -s 'https://code.blicky.net/yorhel/mithril-vndb/raw/branch/next/mithril.js' -o $@

# TODO: Custom bundle with only the stuff we use
js/.gen/d3.js: | js/.gen
	curl -s 'https://d3js.org/d3.v7.min.js' -o $@

js/.gen/types.js: util/jsgen.pl lib/VNDB/Types.pm lib/VNWeb/Validation.pm | js/.gen
	util/jsgen.pl types >$@

js/.gen/user.js: util/jsgen.pl lib/VNWeb/TimeZone.pm | js/.gen
	util/jsgen.pl user >$@

js/.gen/extlinks.js: util/jsgen.pl lib/VNDB/ExtLinks.pm | js/.gen
	util/jsgen.pl extlinks >$@

${JS_BUNDLE_OUT}: %.js: | static/g
	cd js && perl -Mautodie -pe 'if(/^\@include (.+)/) { open F, $$1; local$$/=undef; $$_="/* start of $$1 */\n(()=>{\n".<F>."})();\n/* end of $$1 */\n\n" }' ../$< >../$@

${JS_BUNDLE_MIN}: %.min.js: %.js
	uglifyjs $< --comments '/(@license|@source|SPDX-)/' --compress 'pure_getters,keep_fargs=false,unsafe_comps,unsafe' | uglifyjs --mangle --comments all -o $@




# Multi

# may wait indefinitely, ^C and kill -9 in that case
define multi-stop
	if [ -s data/multi.pid ]; then\
	  kill `cat data/multi.pid`;\
	  while [ -s data/multi.pid ]; do\
	    if kill -0 `cat data/multi.pid`; then sleep 1;\
	    else rm -f data/multi.pid; fi\
	  done;\
	fi
endef

multi-stop:
	$(multi-stop)

multi-start:
	util/multi.pl

multi-restart:
	$(multi-stop)
	util/multi.pl
