package VNWeb::TimeZone;

use v5.28;
use warnings;
use TUWF;
use VNWeb::Auth;
use Exporter 'import';

return 1 if $main::ONLYAPI;

our @EXPORT = ('@ZONES', '%ZONES');

# All cities, including aliases for other timezones but excluding "country"
# aliases to keep the list sane.
# find /usr/share/zoneinfo -type f -printf '%P\n' | grep '/' | grep -vE '^(Etc|Brazil|Chile|Mexico|US|Canada)'
our @ZONES = qw{
    UTC
    Africa/El_Aaiun
    Africa/Ndjamena
    Africa/Maputo
    Africa/Luanda
    Africa/Johannesburg
    Africa/Douala
    Africa/Monrovia
    Africa/Lome
    Africa/Kampala
    Africa/Nouakchott
    Africa/Dakar
    Africa/Banjul
    Africa/Maseru
    Africa/Abidjan
    Africa/Gaborone
    Africa/Harare
    Africa/Lusaka
    Africa/Malabo
    Africa/Kigali
    Africa/Cairo
    Africa/Timbuktu
    Africa/Asmara
    Africa/Ouagadougou
    Africa/Tripoli
    Africa/Libreville
    Africa/Brazzaville
    Africa/Lagos
    Africa/Addis_Ababa
    Africa/Freetown
    Africa/Windhoek
    Africa/Ceuta
    Africa/Casablanca
    Africa/Porto-Novo
    Africa/Bangui
    Africa/Juba
    Africa/Mogadishu
    Africa/Blantyre
    Africa/Accra
    Africa/Kinshasa
    Africa/Bissau
    Africa/Bamako
    Africa/Conakry
    Africa/Mbabane
    Africa/Niamey
    Africa/Tunis
    Africa/Algiers
    Africa/Lubumbashi
    Africa/Asmera
    Africa/Sao_Tome
    Africa/Dar_es_Salaam
    Africa/Bujumbura
    Africa/Nairobi
    Africa/Djibouti
    Africa/Khartoum
    Arctic/Longyearbyen
    Pacific/Wake
    Pacific/Niue
    Pacific/Norfolk
    Pacific/Fiji
    Pacific/Chuuk
    Pacific/Tongatapu
    Pacific/Auckland
    Pacific/Pitcairn
    Pacific/Palau
    Pacific/Kiritimati
    Pacific/Kanton
    Pacific/Chatham
    Pacific/Marquesas
    Pacific/Apia
    Pacific/Pago_Pago
    Pacific/Honolulu
    Pacific/Wallis
    Pacific/Truk
    Pacific/Guam
    Pacific/Funafuti
    Pacific/Fakaofo
    Pacific/Midway
    Pacific/Ponape
    Pacific/Rarotonga
    Pacific/Kosrae
    Pacific/Samoa
    Pacific/Yap
    Pacific/Gambier
    Pacific/Pohnpei
    Pacific/Tarawa
    Pacific/Tahiti
    Pacific/Efate
    Pacific/Kwajalein
    Pacific/Johnston
    Pacific/Enderbury
    Pacific/Bougainville
    Pacific/Easter
    Pacific/Guadalcanal
    Pacific/Port_Moresby
    Pacific/Noumea
    Pacific/Nauru
    Pacific/Saipan
    Pacific/Majuro
    Pacific/Galapagos
    America/Creston
    America/Fort_Nelson
    America/Inuvik
    America/Santiago
    America/Mendoza
    America/Indianapolis
    America/Cambridge_Bay
    America/Metlakatla
    America/Menominee
    America/Iqaluit
    America/Denver
    America/Port_of_Spain
    America/Knox_IN
    America/Atka
    America/La_Paz
    America/Caracas
    America/Fort_Wayne
    America/Shiprock
    America/Guatemala
    America/Puerto_Rico
    America/Fortaleza
    America/El_Salvador
    America/Bogota
    America/Havana
    America/Whitehorse
    America/Nuuk
    America/Matamoros
    America/Rio_Branco
    America/Curacao
    America/Porto_Velho
    America/Indiana/Indianapolis
    America/Indiana/Winamac
    America/Indiana/Vevay
    America/Indiana/Petersburg
    America/Indiana/Tell_City
    America/Indiana/Marengo
    America/Indiana/Vincennes
    America/Indiana/Knox
    America/Cuiaba
    America/Martinique
    America/Thule
    America/Belem
    America/Dawson
    America/Port-au-Prince
    America/Grand_Turk
    America/Belize
    America/Goose_Bay
    America/Swift_Current
    America/New_York
    America/Tortola
    America/Danmarkshavn
    America/Sao_Paulo
    America/Asuncion
    America/Jamaica
    America/Ensenada
    America/Catamarca
    America/Bahia
    America/Scoresbysund
    America/Ojinaga
    America/Yellowknife
    America/Maceio
    America/Argentina/Mendoza
    America/Argentina/Rio_Gallegos
    America/Argentina/Catamarca
    America/Argentina/San_Juan
    America/Argentina/La_Rioja
    America/Argentina/Ushuaia
    America/Argentina/ComodRivadavia
    America/Argentina/Salta
    America/Argentina/Buenos_Aires
    America/Argentina/San_Luis
    America/Argentina/Jujuy
    America/Argentina/Tucuman
    America/Argentina/Cordoba
    America/Panama
    America/Cancun
    America/Santa_Isabel
    America/Bahia_Banderas
    America/Miquelon
    America/Cayenne
    America/Campo_Grande
    America/Regina
    America/St_Vincent
    America/Eirunepe
    America/Guyana
    America/Adak
    America/Kentucky/Monticello
    America/Kentucky/Louisville
    America/Chicago
    America/Marigot
    America/Kralendijk
    America/Tegucigalpa
    America/Lima
    America/Coral_Harbour
    America/Mazatlan
    America/St_Kitts
    America/Buenos_Aires
    America/Thunder_Bay
    America/Detroit
    America/Rainy_River
    America/Hermosillo
    America/Noronha
    America/Santarem
    America/Nome
    America/Barbados
    America/Guadeloupe
    America/Jujuy
    America/Punta_Arenas
    America/Montreal
    America/Chihuahua
    America/St_Johns
    America/Porto_Acre
    America/Yakutat
    America/Anguilla
    America/Resolute
    America/Cayman
    America/Juneau
    America/Nipigon
    America/Moncton
    America/Dominica
    America/Grenada
    America/Atikokan
    America/Boise
    America/Tijuana
    America/St_Barthelemy
    America/Los_Angeles
    America/Merida
    America/Antigua
    America/Paramaribo
    America/Monterrey
    America/Manaus
    America/Sitka
    America/Toronto
    America/Glace_Bay
    America/Vancouver
    America/Santo_Domingo
    America/St_Thomas
    America/Virgin
    America/Godthab
    America/Dawson_Creek
    America/Halifax
    America/Louisville
    America/Anchorage
    America/Rankin_Inlet
    America/Nassau
    America/Aruba
    America/Pangnirtung
    America/Blanc-Sablon
    America/Boa_Vista
    America/North_Dakota/Center
    America/North_Dakota/New_Salem
    America/North_Dakota/Beulah
    America/Mexico_City
    America/Cordoba
    America/Phoenix
    America/Costa_Rica
    America/Araguaina
    America/Edmonton
    America/Managua
    America/Montevideo
    America/Lower_Princes
    America/Montserrat
    America/Guayaquil
    America/Recife
    America/St_Lucia
    America/Winnipeg
    America/Rosario
    Atlantic/Jan_Mayen
    Atlantic/Cape_Verde
    Atlantic/Reykjavik
    Atlantic/St_Helena
    Atlantic/Canary
    Atlantic/Bermuda
    Atlantic/Faeroe
    Atlantic/South_Georgia
    Atlantic/Stanley
    Atlantic/Madeira
    Atlantic/Faroe
    Atlantic/Azores
    Europe/Rome
    Europe/Zaporozhye
    Europe/Astrakhan
    Europe/Vaduz
    Europe/Kyiv
    Europe/Ljubljana
    Europe/Vilnius
    Europe/Tiraspol
    Europe/Tallinn
    Europe/Belgrade
    Europe/Bucharest
    Europe/Luxembourg
    Europe/Kaliningrad
    Europe/Belfast
    Europe/Vatican
    Europe/Riga
    Europe/Moscow
    Europe/Budapest
    Europe/Athens
    Europe/Monaco
    Europe/Andorra
    Europe/Gibraltar
    Europe/Sarajevo
    Europe/Prague
    Europe/Istanbul
    Europe/Berlin
    Europe/Saratov
    Europe/Skopje
    Europe/Warsaw
    Europe/Stockholm
    Europe/Volgograd
    Europe/Mariehamn
    Europe/Lisbon
    Europe/Minsk
    Europe/Jersey
    Europe/Oslo
    Europe/San_Marino
    Europe/Amsterdam
    Europe/Busingen
    Europe/Copenhagen
    Europe/Helsinki
    Europe/Bratislava
    Europe/Sofia
    Europe/Kirov
    Europe/Podgorica
    Europe/Uzhgorod
    Europe/Malta
    Europe/Isle_of_Man
    Europe/Ulyanovsk
    Europe/Dublin
    Europe/Paris
    Europe/Brussels
    Europe/Nicosia
    Europe/Guernsey
    Europe/Madrid
    Europe/London
    Europe/Chisinau
    Europe/Samara
    Europe/Kiev
    Europe/Zagreb
    Europe/Zurich
    Europe/Simferopol
    Europe/Tirane
    Europe/Vienna
    Asia/Aqtobe
    Asia/Hovd
    Asia/Macao
    Asia/Seoul
    Asia/Irkutsk
    Asia/Riyadh
    Asia/Kathmandu
    Asia/Dili
    Asia/Karachi
    Asia/Macau
    Asia/Ashgabat
    Asia/Ulan_Bator
    Asia/Dacca
    Asia/Ulaanbaatar
    Asia/Vientiane
    Asia/Omsk
    Asia/Baghdad
    Asia/Hong_Kong
    Asia/Krasnoyarsk
    Asia/Colombo
    Asia/Ust-Nera
    Asia/Amman
    Asia/Bangkok
    Asia/Tbilisi
    Asia/Tomsk
    Asia/Gaza
    Asia/Barnaul
    Asia/Urumqi
    Asia/Beirut
    Asia/Famagusta
    Asia/Tel_Aviv
    Asia/Ho_Chi_Minh
    Asia/Taipei
    Asia/Harbin
    Asia/Thimbu
    Asia/Istanbul
    Asia/Srednekolymsk
    Asia/Ujung_Pandang
    Asia/Khandyga
    Asia/Sakhalin
    Asia/Chongqing
    Asia/Samarkand
    Asia/Bahrain
    Asia/Tashkent
    Asia/Tehran
    Asia/Qatar
    Asia/Ashkhabad
    Asia/Oral
    Asia/Kuala_Lumpur
    Asia/Singapore
    Asia/Kabul
    Asia/Anadyr
    Asia/Calcutta
    Asia/Jayapura
    Asia/Novokuznetsk
    Asia/Vladivostok
    Asia/Novosibirsk
    Asia/Jerusalem
    Asia/Kuwait
    Asia/Aden
    Asia/Dubai
    Asia/Makassar
    Asia/Brunei
    Asia/Kamchatka
    Asia/Magadan
    Asia/Jakarta
    Asia/Chungking
    Asia/Dhaka
    Asia/Hebron
    Asia/Kuching
    Asia/Aqtau
    Asia/Dushanbe
    Asia/Yakutsk
    Asia/Yerevan
    Asia/Nicosia
    Asia/Yangon
    Asia/Muscat
    Asia/Baku
    Asia/Tokyo
    Asia/Damascus
    Asia/Kashgar
    Asia/Manila
    Asia/Rangoon
    Asia/Qostanay
    Asia/Pontianak
    Asia/Qyzylorda
    Asia/Shanghai
    Asia/Thimphu
    Asia/Yekaterinburg
    Asia/Almaty
    Asia/Chita
    Asia/Atyrau
    Asia/Phnom_Penh
    Asia/Pyongyang
    Asia/Choibalsan
    Asia/Katmandu
    Asia/Saigon
    Asia/Kolkata
    Asia/Bishkek
    Antarctica/Troll
    Antarctica/Davis
    Antarctica/Mawson
    Antarctica/Macquarie
    Antarctica/South_Pole
    Antarctica/DumontDUrville
    Antarctica/McMurdo
    Antarctica/Casey
    Antarctica/Palmer
    Antarctica/Syowa
    Antarctica/Vostok
    Antarctica/Rothera
    Australia/Tasmania
    Australia/Melbourne
    Australia/North
    Australia/Adelaide
    Australia/South
    Australia/Darwin
    Australia/Sydney
    Australia/Currie
    Australia/ACT
    Australia/Broken_Hill
    Australia/Queensland
    Australia/Lord_Howe
    Australia/Brisbane
    Australia/Perth
    Australia/West
    Australia/Hobart
    Australia/Lindeman
    Australia/Eucla
    Australia/Canberra
    Australia/NSW
    Australia/LHI
    Australia/Victoria
    Australia/Yancowinna
    Indian/Maldives
    Indian/Kerguelen
    Indian/Mayotte
    Indian/Reunion
    Indian/Comoro
    Indian/Antananarivo
    Indian/Christmas
    Indian/Mauritius
    Indian/Chagos
    Indian/Mahe
    Indian/Cocos
};
our %ZONES = map +($_,1), @ZONES;

TUWF::hook before => sub {
    $ENV{TZ} = auth->pref('timezone') || 'UTC';
};

1;
